server:
  port: 10001

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    port: 6379
    host: 124.222.56.141
    password: Yi1Ge2Ren3Redis.

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml   # mapper扫描路径  mapper.product
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.deep.product: info