server:
  port: 13000
spring:
  application:
    name: mall-coupon
  # MySQL配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mall.com:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysqlroot
  redis:
    port: 6379
    host: mall.com
    password: redisroot

  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: mall.com:8848
        namespace: 4f3b5226-066e-48e2-b7a6-d71f99290479

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml   # mapper扫描路径
  global-config:
    db-config:
      id-type: auto