server:
  port: 9000
spring:
  application:
    name: mall-order
  # MySQL配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mall.com:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysqlroot
  redis:
    port: 6379
    host: mall.com
    password: redisroot
  cloud:
    nacos:
      discovery: # 注册中心
        server-addr: mall.com:8848
        namespace: 4f3b5226-066e-48e2-b7a6-d71f99290479
  rabbitmq:
    host: mall.com
    port: 5672
    username: admin
    password: rabbitmqroot
    virtual-host: /
    publisher-confirm-type: correlated  # 消息发送到服务器确认
    publisher-returns: true # 消息抵达队列确认
    template:
      mandatory: true # 只要抵达队列就会被异步优先回调
    listener:
      simple:
        acknowledge-mode: manual  # manual手动确认消息

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  # 模板引擎
  thymeleaf:
    cache: false  # 关闭thymeleaf缓存（开发期间可以实时看到页面变化，上线后开启缓存可以提高性能）

# mapper扫描路径
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml   # mapper扫描路径
  global-config:
    db-config:
      id-type: auto # 主键自增

logging:
  level:
    com.deep.order: info