server:
  port: 10002

spring:
  application:
    name: mall-search
  redis:
    port: 6379
    host: mall.com
    password: redisroot
  cloud:
    # nacos配置
    nacos:
      discovery: # 注册中心
        server-addr: mall.com:8848
        namespace: 4f3b5226-066e-48e2-b7a6-d71f99290479

es:
  host: mall.com
  port: 9200

logging:
  level:
    com.deep.search: info