server:
  port: 10002

spring:
  application:
    name: mall-tiny-search
  redis:
    port: 6379
    host: 124.222.56.141
    password: Yi1Ge2Ren3Redis.
  cloud:
    # nacos配置
    nacos:
      discovery: # 注册中心
        server-addr: 124.222.56.141:8848
        namespace: 4f3b5226-066e-48e2-b7a6-d71f99290479

es:
  host: 124.222.56.141
  port: 9200

logging:
  level:
    com.deep.search: info