server:
  port: 14000
spring:
  application:
    name: mall-seckill

  redis:
    port: 6379
    host: 124.222.56.141
    password: Yi1Ge2Ren3Redis.

  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: 124.222.56.141:8848
        namespace: 4f3b5226-066e-48e2-b7a6-d71f99290479

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss